# Dependabot will run on day 20 of each month at 01:42 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '42 1 20 * *'
    open-pull-requests-limit: 15
    labels:
      - 'dependencies'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '42 1 20 * *'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 15
